### ISSUE TITLE
compilazione

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ncurses#1]
Assicurati di aver installato il pacchetto libncurses5-dev

Dammi un ok quando riesci a compilare ed eseguire il programma hello

**Comment by lucifero55** [comment]
Se lancio make mi da errore.

**Comment by lucifero55** [comment]
modificandolo il file Makefile non lo da più.

**Comment by lucifero55** [comment]
mandato in esecuzione con successo

**Comment by FabioZTessitore** [comment]
che modifica hai dovuto effettuare?
