### ISSUE TITLE
mad text

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ncurses#10]
![mad](https://cloud.githubusercontent.com/assets/3002194/19692888/f0f83f34-9ad9-11e6-9e46-c0432951fd4c.png)

**Comment by lucifero55** [comment]
wtf

**Comment by lucifero55** [comment]
Come si fa questa cosa intrigante?

**Comment by lucifero55** [comment]
Me lo dica :c

**Comment by FabioZTessitore** [comment]
La sai fare

Il martedì 25 ottobre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
Ah. Devo fare una quindicina di mvprintw con valori casuali?

**Comment by lucifero55** [comment]
A proposito, python o c?

**Comment by FabioZTessitore** [comment]
Haha
Ogni volta che premi un tasto stampa il carattere in una posizione a caso
con attributi a caso

Il martedì 25 ottobre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Python

I caratteri devono essere inseriti da tastiera e stampati a caso

Il martedì 25 ottobre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
Perchè stampa anche un numero oltre alla carattere?

**Comment by lucifero55** [comment]
Ok ho capito

**Comment by lucifero55** [comment]
Null crea problemi, come faccio?

**Comment by lucifero55** [comment]
Risolto.

**Comment by lucifero55** [comment]
Mi dica se vi piace

**Comment by FabioZTessitore** [comment]
0

Il mercoledì 26 ottobre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
?

**Comment by lucifero55** [comment]
si ho già risolto quel problema :P

**Comment by lucifero55** [comment]
Dovete solo dirmi se va bene.

**Comment by FabioZTessitore** [comment]
invece di quelle brutte chiamate a rand_B() non riesci a fare una sola chiamata a coordinate() che genera sia la riga che la colonna?
suggerimento: tuple

**Comment by lucifero55** [comment]
Like this?

**Comment by lucifero55** [comment]
Non mi avete spiegato a cosa serve refresh()

**Comment by FabioZTessitore** [comment]
Riguardo a refresh:
come lo hai messo non serve proprio a niente. `refresh` va chiamata ogni volta che vuoi aggiornare lo schermo (nel nostro caso ogni volta che un carattere viene stampato in posizione casuale).
Il programma funziona lo stesso anche senza. Dalla documentazione pare che il fenomeno sia legato all'uso dello standard screen e all'uso delle funzioni di input (getch).
Infatti se provi a togliere la riga dell'input vedrai che neanche le intestazioni del programma verranno stampate (niente input, niente refresh automatico dello schermo).
In ogni caso è buona abitudine fare il refresh ogniqualvolta vuoi aggiornare lo schermo.

Tornando al programma, c'è un problema:
si entra nel ciclo, si chiede l'input di un carattere, lo si stampa ... e solo dopo, con l'inizio di un nuovo ciclo, si controlla se bisogna uscire! In altre parole, stampi pure F2?

**Comment by lucifero55** [comment]
'while (n = stdscr.getch()) != curses.KEY_F2:' 
Perchè non funziona?

**Comment by FabioZTessitore** [comment]
forse perché stai usando Python e non C

**Comment by lucifero55** [comment]
Così va bene?
