### ISSUE TITLE
menu

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ncurses#12]
![menu](https://cloud.githubusercontent.com/assets/3002194/19972201/8e7bc1f0-a1e1-11e6-9066-e22c4f7a8099.png)

stavolta oltre ad effettuare una scelta devi illuminare la riga del menu

**Comment by lucifero55** [comment]
Bisogno di delucidazioni.

**Comment by FabioZTessitore** [comment]
1) ripulisca la cartella da file indesiderati
2) chiarisca su cosa necessita delucidazioni

**Comment by lucifero55** [comment]
Quando richiamo posizione in 'stampa_Menu' non ci sono problemi, ma se provo a modificare il suo valore da errore

**Comment by FabioZTessitore** [comment]
ci sono due cartelle menu, cancella quella inutile

**Comment by lucifero55** [comment]
Did it

**Comment by FabioZTessitore** [comment]
ho aggiustato però non mi piace l'idea di avere quella variabile globale.
Non potendo usare gli oggetti puoi riportarla nel main e passarla alle funzioni quando richiesto

ps in ogni caso possiamo andare avanti

**Comment by lucifero55** [comment]
Perchè non chiude la issue? xD
