### ISSUE TITLE
intro alle ncurses

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ncurses#2]
I terminali permettono di essere gestiti in modalità semigrafica. La cosa risulta però difficoltosa (e noiosa). Inoltre non tutti i terminali sono uguali e ciò che funziona su uno potrebbe non funzionare su un altro.

Le librerie ncurses (new curses) nascondono queste difficoltà mettendo a disposizione delle funzioni più semplici e soprattutto indipendenti dal terminale.

Dai un'occhiata al file C/hello/hello.c

**Comment by FabioZTessitore** [comment]
tutto chiaro?

**Comment by lucifero55** [comment]
Si tutto chiaro.

**Comment by FabioZTessitore** [comment]
vedi come spegnere il cursore e come spostarlo

**Comment by lucifero55** [comment]
a cosa serve avere il cursore?

**Comment by FabioZTessitore** [comment]
a vedere dove si scrive

**Comment by lucifero55** [comment]
Non so come spostarlo.

**Comment by lucifero55** [comment]
se premo sinistra conta come un tasto e il file termina

**Comment by FabioZTessitore** [comment]
ma che stai tentando di fare???

spostare il cursore significa che puoi decidere dove scrivere sullo schermo

**Comment by lucifero55** [comment]
con il comando move immagino

**Comment by FabioZTessitore** [comment]
si ma lo puoi spostare anche con le funzioni mvprintw ecc ecc così come scritto nei commenti

**Comment by lucifero55** [comment]
Chiaro.

**Comment by FabioZTessitore** [comment]
vedi come ottenere le dimensioni della finestra

**Comment by lucifero55** [comment]
Che cosa carina. 
Tutto chiaro.

**Comment by FabioZTessitore** [comment]
le stesse cose in Python

**Comment by lucifero55** [comment]
Ok chiaro.
