### ISSUE TITLE
angoli

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ncurses#4]
stampare un asterisco ai quattro angoli del terminale

**Comment by lucifero55** [comment]
gli esercizi in C o in Python?

**Comment by FabioZTessitore** [comment]
come preferisci. In genere quando facciamo esercitazioni usiamo Python

**Comment by lucifero55** [comment]
Perchè avete chiamato quella variabile stdsrc?

**Comment by FabioZTessitore** [comment]
È il nome che viene normalmente dato allo standard screen

Il martedì 18 ottobre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
stdscr.addstr(1,COLS,"*")
Una cosa così manda il tilt il programma.

**Comment by FabioZTessitore** [comment]
Certo. Se ci sono COLS colonne è ovvio

Il martedì 18 ottobre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
Ok con COLS-1 funzione, anche se non mi è molto chiaro il modo in cui vengono conteggiate le righe e colonne.

**Comment by lucifero55** [comment]
stdscr.addstr(ROWS-1,COLS-1,"*")
Manda tutto in tilt tutto

**Comment by FabioZTessitore** [comment]
Come sempre in informatica si parte da zero. Cosa non ti è chiaro?

Ps in basso a destra non si può perché dopo aver scritto il carattere il
cursore prova ad andare avanti ma non può

Il martedì 18 ottobre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by lucifero55** [comment]
Mi dica se va bene così

**Comment by lucifero55** [comment]
Se ci sono 20 colonne e il dico metti asterisco a colonna n 19 perchè non dovrebbe funzionare?

**Comment by FabioZTessitore** [comment]
Solo l'ultima riga crea problemi  le altre no

Il martedì 18 ottobre 2016, lucifero55 <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
le coordinate che usi non sono corrette. Per esempio l'asterisco in alto a sinistra perché lo metti a (0, 1)?

**Comment by lucifero55** [comment]
fate finta sia 0,0.
All'inizio visto che non andava pensavo che anche la prima riga o colonna potesse dare problemi

**Comment by lucifero55** [comment]
Non cambiare anche la colonna è stato un errore di distrazione

**Comment by FabioZTessitore** [comment]
vabbé penso tu abbia capito
