### ISSUE TITLE
attributi

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ncurses#5]
I caratteri possono essere visualizzati
con vari effetti speciali (es. sottolineato, grassetto, ecc.).
Le librerie ncurses utilizzano gli attributi
per modificare le caratteristiche del testo.

Dai un'occhiata al file C/attrs/attrs.c

**Comment by lucifero55** [comment]
Non c'è

**Comment by FabioZTessitore** [comment]
e dammi il tempo, vedi anche attrs2.c

**Comment by lucifero55** [comment]
Tutto chiaro

**Comment by FabioZTessitore** [comment]
è arrivato il momento dei colori

**Comment by FabioZTessitore** [comment]
i colori standard possono essere modificati
se il terminale risponde true a can_change_color().
Nel caso, si usa `init_color(COLOR_RED, 1000, 700, 700)` (crea un rosa)
Attenzione: tutte le stringhe stampate in rosso diventeranno rosa
anche quelle stampate in precedenza!

**Comment by lucifero55** [comment]
Non ho capito 'exit(1)'

**Comment by FabioZTessitore** [comment]
in caso di errore bisogna terminare immediatamente il programma e ci pensa exit().
Il valore 1 (non zero) indica al sistema operativo che c'è stato un problema

**Comment by FabioZTessitore** [comment]
ho inviato anche chgat (change attrib) per cambiare attributi a testo già stampato e la versione Python delle cose viste, quando tutto chiaro passa agli esercizi
