### ISSUE TITLE
disegna quadrati

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ncurses#6]
cerca di fare qualcosa del genere (ovviamente i moduli)

![schermata da 2016-10-18 21-00-00](https://cloud.githubusercontent.com/assets/3002194/19492169/e424965e-9575-11e6-9021-62e43845e591.png)

**Comment by lucifero55** [comment]
Dove sono i problemi?

**Comment by FabioZTessitore** [comment]
in your head, in your head ... they're fighting

**Comment by lucifero55** [comment]
Mi aiuti xD
Non so come far funzionare i moduli. 
Cosa va messo? E cosa no?

**Comment by lucifero55** [comment]
Mi aiuti xD
Non so come far funzionare i moduli. 
Cosa va messo? E cosa no?

**Comment by FabioZTessitore** [comment]
controlla le costanti `COLOR_GREEN`

**Comment by lucifero55** [comment]
va bene?

**Comment by FabioZTessitore** [comment]
si, però cambia la funzione in modo tale che accetti le coordinate di partenza e il lato del quadrato
