### ISSUE TITLE
disegna scacchiera

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ncurses#7]
![schermata da 2016-10-18 21-01-58](https://cloud.githubusercontent.com/assets/3002194/19492229/26788a38-9576-11e6-8e3b-2417ecb54e63.png)

**Comment by lucifero55** [comment]
Per diversi problemi ho usato nano, e l'ho mandato appena ha iniziato a funzionare avevo troppa voglia di vedere se riuscivo a farlo.
Non mi falci lo sistemerò e vedrò come renderlo più semplice haha

**Comment by lucifero55** [comment]
PS stdscr è un nome troppo fastidioso, c'è qualche alternativa?

**Comment by lucifero55** [comment]
Ne complesso come vi sembra?

**Comment by lucifero55** [comment]
Vorrei creare una funzione patternQuadrati() con all'interno areaColorata()
e poi la funzione scacchiera() con all'interno patternQuadrati()
Devo lavorare così?

**Comment by FabioZTessitore** [comment]
si

**Comment by lucifero55** [comment]
ho mandato un crea.py per scacchiera.py ma credo di aver reso tutto più complesso di quanto dovesse essere. 
Mi dica lei.

**Comment by lucifero55** [comment]
https://toggl.com/programming-princess

**Comment by FabioZTessitore** [comment]
in effetti è un po' più complesso di quello che potrebbe essere ma va bene.
prova a fare la scacchiera

ps. anche qui la funzione per la stampa del quadrato prende le coordinate di due punti invece del lato (a questo punto puoi pure lasciare così)

**Comment by lucifero55** [comment]
ps. anche qui la funzione per la stampa del quadrato prende le coordinate di due punti invece del lato (a questo punto puoi pure lasciare così)

Non ho capito.

**Comment by lucifero55** [comment]
Vedete va vi piace.

**Comment by FabioZTessitore** [comment]
lo hai mandato in esecuzione vero?

**Comment by lucifero55** [comment]
certo

**Comment by FabioZTessitore** [comment]
ma non parte

**Comment by lucifero55** [comment]
![scacchiera](https://cloud.githubusercontent.com/assets/16176113/19577947/bad9d0a2-9719-11e6-8a45-359b75e1d1d0.png)

**Comment by FabioZTessitore** [comment]
a me non parte

**Comment by lucifero55** [comment]
ora?

**Comment by FabioZTessitore** [comment]
no

**Comment by lucifero55** [comment]
Cosa esce?

**Comment by FabioZTessitore** [comment]
errori haha

**Comment by lucifero55** [comment]
a me non escono quindi non so dove mettere mano haha

**Comment by lucifero55** [comment]
Qualcosa non va nel codice?

**Comment by FabioZTessitore** [comment]
cancella i file inutili (pyc) e rifai il commit

**Comment by FabioZTessitore** [comment]
e ovviamente push

**Comment by lucifero55** [comment]
ora?

**Comment by FabioZTessitore** [comment]
no

**Comment by FabioZTessitore** [comment]
non mi hai inviato i nuovi file, quelli su github sono di 18 min fa e oltre

**Comment by lucifero55** [comment]
Adesso? :/
Sono un po' confuso haha

**Comment by FabioZTessitore** [comment]
niente da fare

**Comment by lucifero55** [comment]
T.T

**Comment by lucifero55** [comment]
Qual'è il problema?

**Comment by FabioZTessitore** [comment]
ho capito qual è il problema
ha fatto una scacchiera enorme e non ci entra nel mio terminale. Se metto full screen va
