### ISSUE TITLE
input

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ncurses#8]
Le funzioni per l'input sono:

scanw(): equivalente di scanf()
getch(): equivalente di getchar(), legge un carattere
getstr(): equivalente di gets(), legge una stringa

**Comment by lucifero55** [comment]
Chiaro. Vuole che faccia un programma?

**Comment by FabioZTessitore** [comment]
hai avuto un'ispirazione?

**Comment by FabioZTessitore** [comment]
ho inviato input caratteri

**Comment by lucifero55** [comment]
Chiaro

**Comment by lucifero55** [comment]
Capito come funziona il file che avete 'pushato'.
