### ISSUE TITLE
guess

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/ncurses#9]
ricarica guess in una cartella
e diamogli un'interfaccia ncurses

![guess1](https://cloud.githubusercontent.com/assets/3002194/19609687/dc5203a2-97d8-11e6-98cc-8a970ed5f7f7.png)

![guess2](https://cloud.githubusercontent.com/assets/3002194/19609690/e12414ec-97d8-11e6-8d9a-289c20d7cf00.png)

**Comment by lucifero55** [comment]
come funziona veramente refresh()?
Se davvero manda sullo schermo fisico le cose per farmele vedere, perchè il programma funziona anche senza?

**Comment by lucifero55** [comment]
Come faccio funzionare come si deve guess_Domanda?

**Comment by FabioZTessitore** [comment]
siccome chiedi l'input all'utente è il caso di rendere visibile il cursore

**Comment by FabioZTessitore** [comment]
quando devi pulire una linea puo' bastare la stampa del \n

**Comment by FabioZTessitore** [comment]
per qualche motivo non dà indicazioni se la risposta data è troppo piccola o troppo grande

**Comment by FabioZTessitore** [comment]
prova a mettere curs_set(1) e vedi che migliora

**Comment by lucifero55** [comment]
Done.

**Comment by FabioZTessitore** [comment]
in questo modo non solo si vede dove si aspetta l'input, ma quando il programma termina e ti chiede se vuoi rigiocare, premendo y ti accorgi che non devi battere invio
